-- MySQL Script generated by MySQL Workbench
-- Thu Nov 20 17:31:43 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema car
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema car
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `car` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;

USE `car` ;

-- -----------------------------------------------------
-- Table `car`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car`.`categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(40) NOT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  `valorDiariaPadrao` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `car`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `email` VARCHAR(120) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `dtCadastro` DATE NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `cpf` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `car`.`filial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car`.`filial` (
  `idFilial` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `cidade` VARCHAR(80) NOT NULL,
  `uf` CHAR(2) NOT NULL,
  PRIMARY KEY (`idFilial`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `car`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car`.`funcionario` (
  `idFunc` INT NOT NULL AUTO_INCREMENT,
  `idFilial` INT NOT NULL,
  `nome` VARCHAR(80) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `email` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`idFunc`),
  UNIQUE INDEX `cpf` (`cpf` ASC) VISIBLE,
  INDEX `fk_func_filial` (`idFilial` ASC) VISIBLE,
  CONSTRAINT `fk_func_filial`
    FOREIGN KEY (`idFilial`)
    REFERENCES `car`.`filial` (`idFilial`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `car`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car`.`veiculo` (
  `idVeiculo` INT NOT NULL AUTO_INCREMENT,
  `idCategoria` INT NOT NULL,
  `idFilial` INT NOT NULL,
  `placa` CHAR(7) NOT NULL,
  `renavam` CHAR(11) NOT NULL,
  `marca` VARCHAR(80) NOT NULL,
  `modelo` VARCHAR(80) NOT NULL,
  `ano` YEAR NOT NULL,
  `statusVeiculo` TINYINT NOT NULL COMMENT 'AT=Ativo, MA=Manutenção, IN=Indisponível',
  PRIMARY KEY (`idVeiculo`),
  UNIQUE INDEX `placa` (`placa` ASC) VISIBLE,
  UNIQUE INDEX `renavam` (`renavam` ASC) VISIBLE,
  INDEX `fk_vei_categoria` (`idCategoria` ASC) VISIBLE,
  INDEX `fk_vei_filial` (`idFilial` ASC) VISIBLE,
  CONSTRAINT `fk_vei_categoria`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `car`.`categoria` (`idCategoria`),
  CONSTRAINT `fk_vei_filial`
    FOREIGN KEY (`idFilial`)
    REFERENCES `car`.`filial` (`idFilial`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `car`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car`.`reserva` (
  `idReserva` INT NOT NULL AUTO_INCREMENT,
  `idCliente` INT NOT NULL,
  `idVeiculo` INT NOT NULL,
  `idFilialRetirada` INT NOT NULL,
  `idFilialDevolucaoPrev` INT NOT NULL,
  `dtInicioPrev` DATETIME NOT NULL,
  `dtFimPrev` DATETIME NOT NULL,
  `statusReserva` TINYINT NOT NULL COMMENT 'AB=Aberta, CA=Cancelada, FI=Finalizada',
  PRIMARY KEY (`idReserva`),
  INDEX `fk_res_cliente` (`idCliente` ASC) VISIBLE,
  INDEX `fk_res_vei` (`idVeiculo` ASC) VISIBLE,
  INDEX `fk_res_filial_ret` (`idFilialRetirada` ASC) VISIBLE,
  INDEX `fk_res_filial_dev_prev` (`idFilialDevolucaoPrev` ASC) VISIBLE,
  CONSTRAINT `fk_res_cliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `car`.`cliente` (`idCliente`),
  CONSTRAINT `fk_res_filial_dev_prev`
    FOREIGN KEY (`idFilialDevolucaoPrev`)
    REFERENCES `car`.`filial` (`idFilial`),
  CONSTRAINT `fk_res_filial_ret`
    FOREIGN KEY (`idFilialRetirada`)
    REFERENCES `car`.`filial` (`idFilial`),
  CONSTRAINT `fk_res_vei`
    FOREIGN KEY (`idVeiculo`)
    REFERENCES `car`.`veiculo` (`idVeiculo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `car`.`locacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car`.`locacao` (
  `idLocacao` INT NOT NULL AUTO_INCREMENT,
  `idReserva` INT NOT NULL,
  `idCliente` INT NOT NULL,
  `idVeiculo` INT NOT NULL,
  `idFilialRetirada` INT NOT NULL,
  `dtRetirada` DATETIME NOT NULL,
  `kmRetirada` INT NOT NULL,
  `idFilialDevolucao` INT NOT NULL,
  `dtDevolucao` DATETIME NULL DEFAULT NULL,
  `kmDevolucao` INT NULL DEFAULT NULL,
  `valorDiaria` DECIMAL(10,2) NOT NULL,
  `taxas` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `multa` DECIMAL(10,2) NULL DEFAULT '0.00',
  `valorFinal` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`idLocacao`),
  INDEX `fk_loc_cliente` (`idCliente` ASC) VISIBLE,
  INDEX `fk_loc_veiculo` (`idVeiculo` ASC) VISIBLE,
  INDEX `fk_loc_filial_ret` (`idFilialRetirada` ASC) VISIBLE,
  INDEX `fk_loc_filial_dev` (`idFilialDevolucao` ASC) VISIBLE,
  INDEX `fk_locacao_reserva1_idx` (`idReserva` ASC) VISIBLE,
  CONSTRAINT `fk_loc_cliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `car`.`cliente` (`idCliente`),
  CONSTRAINT `fk_loc_filial_dev`
    FOREIGN KEY (`idFilialDevolucao`)
    REFERENCES `car`.`filial` (`idFilial`),
  CONSTRAINT `fk_loc_filial_ret`
    FOREIGN KEY (`idFilialRetirada`)
    REFERENCES `car`.`filial` (`idFilial`),
  CONSTRAINT `fk_loc_veiculo`
    FOREIGN KEY (`idVeiculo`)
    REFERENCES `car`.`veiculo` (`idVeiculo`),
  CONSTRAINT `fk_locacao_reserva1`
    FOREIGN KEY (`idReserva`)
    REFERENCES `car`.`reserva` (`idReserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
